danger-ahead/roBOT

.gitignore, main.py
The output of definitions have been cleared and simplified.
this PR creates no additional bugs or issues.
PLS do check.
=> resolved meanings issues

main.py
=> string formating and ending braces removed

main.py
=> added_hit_songs_of_artist

main.py
=> fix issue #8

.github/workflows/python-app.yml, main.py, quiz.py
- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update
* OS: Windows 10 and Kali linux
* OS Version: 21H1 and 2021.1
=> Leader output changed

main.py
Fixes #---
Addresses #---
* OS:
* OS Version:
=> added covid report

main.py
Embed display added for search , mean , wiki & covrep
* OS :Windows 10 , Kali linux
* OS Version: 21H1 and 2021.1
=>  embed added for search mean wiki

README.md, docs/DEPENDENCIES.md, docs/SCREENSHOTS.md
Fixes #10 
Addresses #---
* OS: Fedora
* OS Version: 34
=> added DEPENDENCIES.md and updated README.md

main.py, quiz.py
Fixes #---
Addresses #---
* OS:
* OS Version:
=> scores bug fixed

main.py, quiz.py
=> Revert "scores bug fixed"

docs/SCREENSHOTS.md
screenshots in SCREENSHOTS.md deleted
=> screenshots deleted

main.py
=> added db.score_up()

.github/workflows/lint.yml
Fixes #---
Addresses #---
* OS:
* OS Version:
=> lint added

commands/api_commands.py
Fixes #---
Addresses #---
* OS:
* OS Version:
=> Added weather icons

commands/help.py
Removed `if-else` as it is asked in issue #66 and used `dictionary` for search. Improved visuals by adding Emojis in title of the embed.
Fixes  #66 
Addresses #`commands/help.py`
Functionality and Visual updates in help command
* OS: linux
* OS Version: Kernel 5.4.0-73-generic
=> Removed if-else from help.py and used dictionary

main.py
Fixes #70, added lines indicating successful execution.
=> Fixed #70 - Lines indicating successful execution are missing

commands/scripts/moderate_words.txt
Fixes #71 
Addresses #---
* OS:
* OS Version:
=> Made 3 different lang sections, added new words.

CONTRIBUTING.MD
Signed-off-by: Soham Banerjee <sohambanerjee4abc@hotmail.com>
Added Contributing.md
=> Contributing.md added

commands/hi_contrib.py
Changed the welcome message of the bot.
Fixes #---
Addresses #---
* OS: Windows 10
* OS Version: latest
The last one is the final outcome.
=> Changed welcome message

commands/scripts/moderate_words.txt
Signed-off-by: Soham Banerjee <sohambanerjee4abc@hotmail.com>
Fixes bug which was resulting in unnecessary warnings
=> moderator words fixed

commands/__init__.py, commands/compliment.py, commands/help.py, commands/hi_contrib.py, main.py
Fixes #---
Added _compliment command which randomly gives the user a compliment as well as fixed a typo in the hi_contrib.py file.
* OS: Windows10
We all feel low at times, the command which I added helps the user cheer up by providing a confidence-boosting compliment.
=> #Resolved 86 Added Compliment command

commands/help.py, docs/COMMANDS.md
Updated the documentation by adding information about _compliment command in help.py and commands.md files.
* OS: Windows10
=> #Resolved 89 Updating documentation part

commands/compliment.py, commands/help.py
Signed-off-by: Soham Banerjee <sohambanerjee4abc@hotmail.com>
Code reformatted
=> code reformatted

README.md
Adding Screenshots, License and restructuring the README
Fixes #93
=> Added Licence and Screenshot in README.

command/general/slomode.py, docs/COMMANDS.md
Fixes #---
Addresses #---
Added slowmode command
I tested it by running a test bot on the same code
* OS:
* OS Version:
=> added slowmode command

command/general/wikipedia.py, requirements.txt
Added Wikipedia search command to the search module
=> Wikipedia search command

command/api/pokemon.py, command/general/f.py, command/general/ptrivia.py, command/general/song.py, command/general/trivia.py, command/general/wea.py
Changed all commands that are using `requests` to `aiohttp` module.
=> changed from requests to aiohttp
